install: # install
	./gradlew clean install
run-dist: # run
	./build/install/app/bin/app
check-updates: #check updates
	./gradlew dependencyUpdates
lint: # checkstyle
	./gradlew checkstyleMain
build: # build
	./gradlew clean build
